@startuml usecase diagram
title Usecase diagram
left to right direction
actor "Bank Staff" as staff
actor "System/Data Scientist" as system
actor "External System" as external_system

rectangle "Bank Customer Classification" {
  usecase "View Classification Results" as view_results
  usecase "Retrain Model" as retrain
}

staff --> view_results
external_system --> view_results
system --> retrain
@enduml